// Mocks generated by Mockito 5.4.6 from annotations
// in volticar_app/test/widget/features/auth/views/login_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:volticar_app/features/auth/viewmodels/auth_viewmodel.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i2.AuthViewModel {
  MockAuthViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoginLoading => (super.noSuchMethod(
        Invocation.getter(#isLoginLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoginSuccess => (super.noSuchMethod(
        Invocation.getter(#isLoginSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get isRegisterLoading => (super.noSuchMethod(
        Invocation.getter(#isRegisterLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isRegisterSuccess => (super.noSuchMethod(
        Invocation.getter(#isRegisterSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get isEmailVerificationLoading => (super.noSuchMethod(
        Invocation.getter(#isEmailVerificationLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isEmailVerificationSuccess => (super.noSuchMethod(
        Invocation.getter(#isEmailVerificationSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get isResetPasswordLoading => (super.noSuchMethod(
        Invocation.getter(#isResetPasswordLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isResetPasswordSuccess => (super.noSuchMethod(
        Invocation.getter(#isResetPasswordSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool isValidEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #isValidEmail,
          [email],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isValidPassword(String? password) => (super.noSuchMethod(
        Invocation.method(
          #isValidPassword,
          [password],
        ),
        returnValue: false,
      ) as bool);

  @override
  void autoClearError() => super.noSuchMethod(
        Invocation.method(
          #autoClearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> sendEmailVerification(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> register({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #username: username,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> checkLoginStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkLoginStatus,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> verifyResetOtp(String? optCode) => (super.noSuchMethod(
        Invocation.method(
          #verifyResetOtp,
          [optCode],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> resetPassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [newPassword],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void resetPasswordState() => super.noSuchMethod(
        Invocation.method(
          #resetPasswordState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
