// Mocks generated by Mockito 5.4.6 from annotations
// in volticar_app/test/widget/features/auth/views/register_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:volticar_app/features/auth/viewmodels/register_viewmodel.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegisterViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterViewModel extends _i1.Mock implements _i2.RegisterViewModel {
  @override
  bool get isRegisterLoading => (super.noSuchMethod(
        Invocation.getter(#isRegisterLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRegisterSuccess => (super.noSuchMethod(
        Invocation.getter(#isRegisterSuccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isEmailVerificationLoading => (super.noSuchMethod(
        Invocation.getter(#isEmailVerificationLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isEmailVerificationSuccess => (super.noSuchMethod(
        Invocation.getter(#isEmailVerificationSuccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isCheckingUsername => (super.noSuchMethod(
        Invocation.getter(#isCheckingUsername),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isUsernameAvailable => (super.noSuchMethod(
        Invocation.getter(#isUsernameAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isValidEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #isValidEmail,
          [email],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isValidPassword(String? password) => (super.noSuchMethod(
        Invocation.method(
          #isValidPassword,
          [password],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isValidUserName(String? username) => (super.noSuchMethod(
        Invocation.method(
          #isValidUserName,
          [username],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> checkUsernameAvailability(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUsernameAvailability,
          [username],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendEmailVerification(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> register({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #username: username,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void markEmailVerificationSuccessAsHandled() => super.noSuchMethod(
        Invocation.method(
          #markEmailVerificationSuccessAsHandled,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markRegisterSuccessAsHandled() => super.noSuchMethod(
        Invocation.method(
          #markRegisterSuccessAsHandled,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void autoClearError() => super.noSuchMethod(
        Invocation.method(
          #autoClearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
