// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKy4kJhqspSCn6dDKQ4wO0qNkABl31kbM',
    appId: '1:427763680887:android:2ec0109f1d256ecf54e872',
    messagingSenderId: '427763680887',
    projectId: 'volticar-e998e',
    storageBucket: 'volticar-e998e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhalu5HAWzH0SemNdTZIK3Ya9-8nfshI8',
    appId: '1:427763680887:web:ef211f011947b14654e872',
    messagingSenderId: '427763680887',
    projectId: 'volticar-e998e',
    authDomain: 'volticar-e998e.firebaseapp.com',
    storageBucket: 'volticar-e998e.firebasestorage.app',
    measurementId: 'G-5HHWP54PC3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT9qGSGIBRgCamedUDqDvx1Kk8Di0JtgY',
    appId: '1:427763680887:ios:86e03de357e77b7154e872',
    messagingSenderId: '427763680887',
    projectId: 'volticar-e998e',
    storageBucket: 'volticar-e998e.firebasestorage.app',
    androidClientId:
        '427763680887-e36f7dr7hv2iuq0tfffoog5ci8u146jb.apps.googleusercontent.com',
    iosClientId:
        '427763680887-rbqgs4mv9jh04tetgqphk7s83928m8bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.volticarApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT9qGSGIBRgCamedUDqDvx1Kk8Di0JtgY',
    appId: '1:427763680887:ios:86e03de357e77b7154e872',
    messagingSenderId: '427763680887',
    projectId: 'volticar-e998e',
    storageBucket: 'volticar-e998e.firebasestorage.app',
    androidClientId:
        '427763680887-e36f7dr7hv2iuq0tfffoog5ci8u146jb.apps.googleusercontent.com',
    iosClientId:
        '427763680887-rbqgs4mv9jh04tetgqphk7s83928m8bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.volticarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhalu5HAWzH0SemNdTZIK3Ya9-8nfshI8',
    appId: '1:427763680887:web:d9c51180031b2afb54e872',
    messagingSenderId: '427763680887',
    projectId: 'volticar-e998e',
    authDomain: 'volticar-e998e.firebaseapp.com',
    storageBucket: 'volticar-e998e.firebasestorage.app',
    measurementId: 'G-FWSS489DFR',
  );
}
